spring:
  ai:
    model:
      chat: openai
    openai:
      base-url: ${AZURE_OPENAI_BASE_URL}
      api-key: ${AZURE_OPENAI_API_KEY}
      chat:
        options:
          model: ${AZURE_OPENAI_DEPLOYMENT}
