apiVersion: v1
kind: Service
metadata:
  name: fleet-routing-platform
spec:
  selector:
    app.kubernetes.io/name: fleet-routing-platform
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
